///////////////////////////////////////////////////////////
//  KPI_Definition_Time_Range.cs
//  Implementation of the Class KPI_Definition_Time_Range
//  Generated by Enterprise Architect
//  Created on:      22-Oct-2015 10:06:06 PM
//  Original author: dnbrandl
//  Code generator/author: kjsmiley
//  Last revised 2016-08-03
//  The KPI Markup Language (KPI-ML) is used courtesy of MESA International. 
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// MESA KPI Definition Time Range class.
/// See http://mesa.org/en/kpiml.asp for more information.
/// </summary>
public class KPI_Definition_Time_Range : MESA.KPIML.KPI_Time_Range
{
#if SUPERSEDED

	/// <summary>
	/// Duration of this Time Range for the KPI Definition.
	/// <i>See standard ISO 22400-1 for syntax. Optional.</i>
	/// </summary>
	public string Duration = "";
	/// <summary>
	/// End point of this Time Range for the KPI Definition
	/// </summary>
	public DateTime EndTime = DateTime.MaxValue;
	/// <summary>
	/// Recurrence of this Time Range for the KPI Definition
	/// <i>See standard ISO 22400-1 for syntax. Optional.</i>
	/// </summary>
	public string Recurrence = "";
	/// <summary>
	/// Start point of this Time Range for the KPI Definition
	/// </summary>
	public DateTime StartTime = DateTime.MinValue;

    /// <summary>
    /// Constructor
    /// </summary>
	public KPI_Definition_Time_Range(){

	}

    /// <summary>
    /// Destructor
    /// </summary>
	~KPI_Definition_Time_Range(){

	}
#endif
}//end KPI_Definition_Time_Range