///////////////////////////////////////////////////////////
//  KPI_Value_Property.cs
//  Implementation of the Class KPI_Value_Property
//  Generated by Enterprise Architect
//  Created on:      22-Oct-2015 10:06:06 PM
//  Original author: dnbrandl
//  Code generator/author: kjsmiley
//  Last revised 2016-08-03
//  The KPI Markup Language (KPI-ML) is used courtesy of MESA International. 
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// MESA KPI Value Property class.
/// See http://mesa.org/en/kpiml.asp for more information.
/// </summary>
public class KPI_Value_Property {

	/// <summary>
	/// Text(s) describing this Property of the KPI Value
	/// </summary>
	public List<string> Description = new List<string>{};
	/// <summary>
	/// Unique identifier for this Property of the KPI Value
	/// <i>(if a numeric value is desired, use LONG instead of ULONG </i>
	/// <i>to maximize compatibility across Java and C#. for a string,</i>
	/// <i>consider using string equivalent of a type such as GUID)</i>
	/// </summary>
	public string ID = "";
	/// <summary>
	/// Value for this Property of the KPI Value. Required.
	/// </summary>
	public string Value = "";
	/// <summary>
	/// This KPI Value may include other KPI Values with the given IDs (??)
	/// </summary>
	public List<KPI_Value_Property> m_KPI_Value_Property = new List<KPI_Value_Property>();

    /// <summary>
    /// Constructor
    /// </summary>
    public KPI_Value_Property()
    {

	}

    /// <summary>
    /// Destructor
    /// </summary>
    ~KPI_Value_Property()
    {

	}

}//end KPI_Value_Property