///////////////////////////////////////////////////////////
//  KPI_Value.cs
//  Implementation of the Class KPI_Value
//  Generated by Enterprise Architect
//  Created on:      22-Oct-2015 10:06:06 PM
//  Original author: dnbrandl
//  Code generator/author: kjsmiley
//  Last revised 2016-08-03
//  The KPI Markup Language (KPI-ML) is used courtesy of MESA International. 
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// MESA KPI Value class.
/// See http://mesa.org/en/kpiml.asp for more information.
/// </summary>
public class KPI_Value {

	/// <summary>
	/// Text(s) with Description of this KPI Value
	/// </summary>
	public List<string> Description = new List<string>{};
	/// <summary>
	/// Unique identifier for this KPI Value
	/// <i>(if a numeric value is desired, use LONG instead of ULONG </i>
	/// <i>to maximize compatibility across Java and C#. for a string,</i>
	/// <i>consider using string equivalent of a type such as GUID)</i>
	/// </summary>
	public string ID = "";
	/// <summary>
	/// Name of this KPI Value
	/// </summary>
	public string Name = "";
	/// <summary>
	/// List of texts describing this KPI Value
	/// Unconstrained, but SI units are preferred.
	/// </summary>
	public string UnitOfMeasure = "";
	/// <summary>
	/// Value of this KPI
	/// <i>(NaN if no value is assigned)</i>
	/// </summary>
	public double Value = System.Double.NaN;
    /// <summary>
    /// KPI Value properties
    /// </summary>
	public List<KPI_Value_Property> m_KPI_Value_Property = new List<KPI_Value_Property>();
    /// <summary>
    /// KPI Value time range
    /// </summary>
	public KPI_Value_Time_Range m_KPI_Value_Time_Range = new KPI_Value_Time_Range();

    /// <summary>
    /// Constructor
    /// </summary>
    public KPI_Value()
    {

	}

    /// <summary>
    /// Destructor
    /// </summary>
    ~KPI_Value()
    {

	}

}//end KPI_Value