///////////////////////////////////////////////////////////
//  KPI_Instance_Property.cs
//  Implementation of the Class KPI_Instance_Property
//  Generated by Enterprise Architect
//  Created on:      22-Oct-2015 10:06:06 PM
//  Original author: dnbrandl
//  Code generator/author: kjsmiley
//  Last revised 2016-08-05
//  The KPI Markup Language (KPI-ML) is used courtesy of MESA International. 
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace MESA.KPIML
{
    /// <summary>
    /// MESA KPI Instance Property class. Referenceable by ID.
    /// See http://mesa.org/en/kpiml.asp and https://github.com/MESAInternational/KPI-ML/ for more information.
    /// </summary>
    public class KPI_Instance_Property
    {
        /// <summary>
        /// Unique identifier for this Property of the KPI Instance
        /// </summary>
        /// <remarks>
        /// <i>(if a numeric value is desired, use LONG instead of ULONG </i>
        /// <i>to maximize compatibility across Java and C#. for a string,</i>
        /// <i>consider using string equivalent of a type such as GUID)</i>
        /// </remarks>
        public string ID = "";

        /// <summary>
        /// Text containing the Value of this Property of the KPI Instance. 
        /// <i>Required.</i>
        /// </summary>
        public string Value = "";

        /// <summary>
        /// List of texts describing this Property of the KPI Instance. 
        /// <i>Optional.</i>
        /// </summary>
        public List<string> Description = new List<string>();

        /// <summary>
        /// This KPI Instance Property may include other KPI Instance Properties 
        /// (embedded, not referenced by IDs)
        /// </summary>
        public List<KPI_Instance_Property> m_KPI_Instance_Property = new List<KPI_Instance_Property>();

        /// <summary>
        /// Constructor (auto-generated)
        /// </summary>
        public KPI_Instance_Property()
        {

        }

        /// <summary>
        /// Destructor (auto-generated)
        /// </summary>
        ~KPI_Instance_Property()
        {

        }

    }//end KPI_Instance_Property
}